name: Check links

on: push

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check links
        run: |
          cd website && bundle install
          cd website && make check_links